### ISSUE TITLE
After installing package running demo programs complain that libmagic is not present

### ISSUE THREAD

**Issue by kerby2000** [dcrblack/snooker-ball-tracker#12]
After installing package running  demo programs complain that **libmagic** is not present 

```
    raise ImportError('failed to find libmagic.  Check your installation')
ImportError: failed to find libmagic.  Check your installation
```

Fixed by manually installing following packages:
```
pip install libmagic
pip install python-magic-bin==0.4.14 
```

Maybe I was doing something wrong but I followed your quick start guide

**Comment by Danthewaann** [comment]
Hi, sorry for not getting back to your issue sooner.

I not 100% certain of this, but I think the reason why you had to manually run `pip install python-magic-bin=0.4.14` is because the `libmagic1` package is not on your system (I'm assuming your running linux).

Based on the docs here https://github.com/ahupp/python-magic#installation I can update the README.md to detail that the libmagic C library needs to be manually installed as well.

Thanks raising this issue! 👍

**Comment by Danthewaann** [comment]
Actually I've re-produced the problem locally. I can add the `python-magic-bin` as a windows specific dependency which should resolve this issue.
